activities/urls.py
from django.urls import path
from activities import views


app_name = 'activities'

urlpatterns = [
    path('', views.index, name='index'),
    path('activity/<int:activity_id>/detail/', views.detail, name='detail'),
    path('activity/<int:activity_id>/detail/edit', views.detail_edit, name='detail'),
    path('activity/add', views.detail_add, name='add'),
    path('activity/upload', views.upload_image, name='upload'),
    path('activity/test', views.test, name='test'),
    # path('profile/', views.profile, name='profile'),
    #
    # path('register/', views.register, name='register'),
    # path('login/', views.login, name='login',),
    # path('logout/', views.logout, name='logout'),
    # path('user/<int:user_id>/profile/', views.profile, name='profile'),
    # # path('user/<int:user_id>/profile/update/', views.profile_update, name='profile_update'),
    # path('user/<int:user_id>/pwdchange/', views.pwd_change, name='pwd_change'),

]

api/urls.py
from django.contrib import admin
from django.urls import path
from api import views




app_name = 'users'

urlpatterns = [

    # path('profile/', views.profile, name='profile'),

    path('settings/switch', views.switch, name='switch'),
    path('icons/find', views.find, name='find'),

    # path('login/', views.login, name='login',),
    # path('logout/', views.logout, name='logout'),
    # path('user/<int:user_id>/profile/', views.profile, name='profile'),
    # # path('user/<int:user_id>/profile/update/', views.profile_update, name='profile_update'),
    # path('user/<int:user_id>/pwdchange/', views.pwd_change, name='pwd_change'),

]

luckySys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('luck/', include('luck.urls')),
    path('activities/', include('activities.urls')),
    path('api/',include('api.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
import re
from users import models

NUM_LETTER = re.compile("^(?!\d+$)[\da-zA-Z_]+$")  # 数字和字母组合，不允许纯数字
FIRST_LETTER = re.compile("^[a-zA-Z\d]")  # 只能以字母开头


def account_name_fomart(Name):
	if NUM_LETTER.search(Name):
		if FIRST_LETTER.search(Name):
			return True
	return False


def email_check(email):
	pattern = re.compile(r"\"?([-_a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
	return re.match(pattern, email)


class RegistrationForm(forms.Form):

	# username = forms.CharField(label='Username', max_length=50)
	# email = forms.EmailField(label='Email',)
	# password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	# password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)
	username = forms.CharField(max_length=50)
	email = forms.EmailField()
	password1 = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_username(self):
		username = self.cleaned_data.get('username')
		if not account_name_fomart(username):
			raise forms.ValidationError("Your UserID must be at least 6 characters long.")
		elif len(username) < 6:
			raise forms.ValidationError("Your UserID must be at least 6 characters long.")
		elif len(username) > 50:
			raise forms.ValidationError("Your UserID is too long.")
		else:
			filter_result = User.objects.filter(username__exact=username)
			if len(filter_result) > 0:
				raise forms.ValidationError("Your UserID already exists.")

		return username

	def clean_email(self):
		email = self.cleaned_data.get('email')

		if email_check(email):
			filter_result = User.objects.filter(email__exact=email)
			if len(filter_result) > 0:
				raise forms.ValidationError("Your email already exists.")
		else:
			raise forms.ValidationError("Please enter a valid email.")

		return email

	def clean_password1(self):
		password1 = self.cleaned_data.get('password1')

		if len(password1) < 6:
			raise forms.ValidationError("Your password is too short.")
		elif len(password1) > 20:
			raise forms.ValidationError("Your password is too long.")

		return password1

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Password mismatch. Please enter again.")

		return password2


class LoginForm(forms.Form):

	username = forms.CharField(label='Username', max_length=50)
	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_username(self):
		username = self.cleaned_data.get('username')

		if email_check(username):
			filter_result = User.objects.filter(email__exact=username)
			if not filter_result:
				raise forms.ValidationError("This email does not exist.")
		else:
			filter_result = User.objects.filter(username__exact=username)
			if not filter_result:
				raise forms.ValidationError("This username does not exist. Please register first.")

		return username


class ProfileForm(forms.Form):

	first_name = forms.CharField(label='First Name', max_length=50, required=False)
	last_name = forms.CharField(label='Last Name', max_length=50, required=False)
	short_number = forms.CharField(label='Short Number', max_length=50, required=False)
	phone_number = forms.CharField(label='Phone Number', max_length=50, required=False)
	experience = forms.CharField(widget=forms.Textarea, label='Experience', max_length=500, required=False)
	skill = forms.CharField(label='Skill',max_length=200, required=False)
	education = forms.CharField(label='Education',max_length=128, required=False)
	job = forms.CharField(label="Job", max_length=64, required=False)
	site_id = forms.fields.IntegerField(widget=widgets.Select(choices=models.Site.objects.values_list('id', 'name'),))
	avatar = forms.ImageField(label='Avatar', required=False)


class PwdChangeForm(forms.Form):
	old_password = forms.CharField(label='Old password', widget=forms.PasswordInput)

	password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_password1(self):
		password1 = self.cleaned_data.get('password1')

		if len(password1) < 6:
			raise forms.ValidationError("Your password is too short.")
		elif len(password1) > 20:
			raise forms.ValidationError("Your password is too long.")

		return password1

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')

		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Password mismatch. Please enter again.")

activities/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.contrib.auth.models import User
from users import models
import os, random
from datetime import datetime
from django.conf import settings
from django.http import JsonResponse


def index(request):

	activities = models.Activity.objects.all()
	if request.method == "GET":
		print(activities)
		return render(request, 'activities/index.html',{'activities': activities})


def detail(request, activity_id):
	activity = get_object_or_404(models.Activity, pk=activity_id )
	print(activity_id)
	return render(request,'activities/detail.html', {'activity':activity})


def detail_edit(request, activity_id):
	activity = get_object_or_404(models.Activity, pk=activity_id)
	if request.method =='POST':
		content = request.POST['content']
		name = request.POST['title']
		activity.content=content
		activity.name = name
		activity.save()
	else:
		content = activity.content
	return render(request,'activities/detail_edit.html',{'activity_id':activity_id, 'content':content, 'activity':activity})


def upload_image(request):
	if request.method =='POST':
		print(request.FILES)
		print(request.FILES['file'])
		data = request.FILES['file']
		img = data.read()
		now_time = datetime.now().strftime('%Y%m%d%H%M%S')
		random_str = "%06d" % random.randint(0,999999)
		file_name = "{}.png".format(now_time+random_str)
		print(img)
		print(file_name)
		try:
			with open(os.path.join(settings.MEDIA_ROOT,'img',file_name),'wb') as f:
				f.write(img)

				pic_path = settings.HOST_URL+'/media/img/'+file_name
				res ={"pic_path": pic_path, "pic_name":file_name}
		except Exception as e:
			print(e)
			print('faill to upload')
			res = {}

		return JsonResponse(res)


def detail_add(request):
	if request.method == 'GET':
		return render(request,'activities/detail_add.html')
	elif request.method == 'POST':
		name = request.POST['title']
		content = request.POST['content']
		time = request.POST['time']
		creator = User.objects.get(pk=request.POST['creator'])
		activity = models.Activity.objects.create(name=name,content=content, time=time, creator=creator)

		return render(request, 'activities/detail_edit.html', {'activity': activity})


def test(request):
	return render(request, 'activities/test.html')

templates/activities/detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-12">
{#                        <h1>{{ activity.name }}</h1>#}
                        <h1>
                            <a href="/activities/activity/{{ activity.id }}/detail"><strong>{{ activity.name }}</strong></a></h3>
                        </h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
        <section class="content">
{#            <div class="row">#}
{#                <div class="col-md-12">#}
{#                    <div class="card card-outline card-blue">#}
{#                        <div class="card-header">#}
{#                            <h3 class="card-title">#}
{#                                <a href="/activities/activity/{{ activity.id }}/detail"><strong>{{ activity.name }}</strong></a></h3>#}
{#                            </h3>#}
{#                            <div class="card-tools">#}
{#                              <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>#}
{#                              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>#}
{#                            </div>#}
{#                        </div>#}
{#                        <!-- /.card-header -->#}
{#                        <div class="card-body pad">#}
{#                            {{ activity.content }}#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <!-- /.col-->#}
{#            </div>#}
{#            <!-- ./row -->#}
            <div class="card card-widget">
              <div class="card-header">
                <div class="user-block">
                  <img class="img-circle" src="/media/{{ user.profile.avatar }}" alt="User Image">
                  <span class="username"><a href="#">{{ activity.creator.first_name }}</a></span>
                  <span class="description">Shared publicly - {{activity.update_time}}</span>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="maximize"><i class="fas fa-expand"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" ><a href="edit"><i class="fas fa-edit"> </i></a></button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                    <p>{{ activity.content|safe }}</p>

                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
                <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
                <span class="float-right text-muted">{{activity.views}} likes</span>
              </div>
              <!-- /.card-body -->
              <div class="card-footer card-comments">
                <div class="card-comment">
                  <!-- User image -->
                  <img class="img-circle img-sm" src="/media/{{ user.profile.avatar }}" alt="User Image">

                  <div class="comment-text">
                    <span class="username">
                      Maria Gonzales
                      <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->
                <div class="card-comment">
                  <!-- User image -->
                  <img class="img-circle img-sm" src="/media/{{ user.profile.avatar }}" alt="User Image">

                  <div class="comment-text">
                    <span class="username">
                      Luna Stark
                      <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                  </div>
                  <!-- /.comment-text -->
                </div>
                <!-- /.card-comment -->
              </div>
              <!-- /.card-footer -->
              <div class="card-footer">
                <form action="#" method="post">
                  <img class="img-fluid img-circle img-sm" src="/media/{{ user.profile.avatar }}" alt="Alt Text">
                  <!-- .img-push is used to add margin to elements next to floating images -->
                  <div class="img-push">
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                  </div>
                </form>
              </div>
              <!-- /.card-footer -->
            </div>
        </section>
    </div>

{% endblock content %}
{% block script %}
    <script>


    </script>
{% endblock script %}

templates/activities/detail_add.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
{#    <body class="hold-transition sidebar-mini">#}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Text Editors</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Text Editors</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title col-sm-8">
                    <input type="text" class="form-control " id="title" value="{{ activity.name }}"/>

              </h3>

              <!-- tools box -->
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="remove" data-toggle="tooltip"
                        title="Remove">
                  <i class="fas fa-times"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body pad">
              <div class="mb-3">
                  <div id="summernote">
                        {{ content|safe }}
                  </div>
                  <button id="submit" class="btn btn-info"  onclick="submit()">提交</button>


              </div>
                <!-- alert 窗口-->
                <div class="alert " style="display:none; position: fixed; top: 50%; left: 50%; min-width: 200px;margin-left: -100px;z-index: 99999;padding: 15px;border:1px solid #d6e9c6;border-radius: 4px;color: #3c763d;background-color: #dff0d8;"></div>
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block script %}
<script>
    var editor = $('#summernote');

  $(function () {
    // Summernote
        editor.summernote({
        height:600,
        callbacks: {
            onImageUpload: function(files) {

            //console.log(123),
            sendFile(files);
            },
        }
        })
  })

function sendFile(files) {
    data = new FormData();
    for(f in files){
       data.append("file", files[f]);
    }

    data.append("csrfmiddlewaretoken",'{{ csrf_token  }}');
    $.ajax({
        data: data,
        type: "POST",
        url: "/activities/activity/upload",
        cache: false,
        contentType: false,
        processData: false,
        success: function(data) {
                console.log(data.pic_path, data.pic_name);
                editor.summernote('insertImage', "http://"+data.pic_path,);
                {#editor.insertImage(welEditable, url);#}
        }
    });
}


function submit(){
      data = new FormData();
      data.append("content", editor.summernote('code'))
     data.append("title",$('#title').val())
      data.append("csrfmiddlewaretoken",'{{ csrf_token  }}');
      data.append('creator', '{{ request.user.id }}')
      data.append('time','2019-09-18' )

      $.ajax({
          data: data,
          type: "POST",
          url: "/activities/activity/add",
          cache: false,
          contentType: false,
          processData: false,
          success: function(data) {
              $('.alert').html('Well Done, saved successfully! ').show().delay(1000).fadeOut()
        }
    });
}






</script>
{% endblock script %}

templates/activities/detail_edit.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
{#    <body class="hold-transition sidebar-mini">#}
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Text Editors</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Text Editors</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-outline card-info">
            <div class="card-header">
              <h3 class="card-title col-sm-8">
                    <input type="text" class="form-control " id="title" value="{{ activity.name }}"/>

              </h3>

              <!-- tools box -->
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fas fa-minus"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="remove" data-toggle="tooltip"
                        title="Remove">
                  <i class="fas fa-times"></i></button>
              </div>
              <!-- /. tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body pad">
              <div class="mb-3">
                  <div id="summernote">
                        {{ content|safe }}
                  </div>
                  <button id="submit" class="btn btn-info"  onclick="submit()">提交</button>


              </div>
                <!-- alert 窗口-->
                <div class="alert " style="display:none; position: fixed; top: 50%; left: 50%; min-width: 200px;margin-left: -100px;z-index: 99999;padding: 15px;border:1px solid #d6e9c6;border-radius: 4px;color: #3c763d;background-color: #dff0d8;"></div>
            </div>
          </div>
        </div>
        <!-- /.col-->
      </div>
      <!-- ./row -->
    </section>
    <!-- /.content -->
  </div>
{% endblock content %}

{% block script %}
<script>
    var editor = $('#summernote');

  $(function () {
    // Summernote
        editor.summernote({
        height:600,
        callbacks: {
            onImageUpload: function(files) {

            //console.log(123),
            sendFile(files);
            },
        }
        })
  })

function sendFile(files) {
    data = new FormData();
    for(f in files){
       data.append("file", files[f]);
    }

    data.append("csrfmiddlewaretoken",'{{ csrf_token  }}');
    $.ajax({
        data: data,
        type: "POST",
        url: "/activities/activity/upload",
        cache: false,
        contentType: false,
        processData: false,
        success: function(data) {
                console.log(data.pic_path, data.pic_name);
                editor.summernote('insertImage', "http://"+data.pic_path,);
                {#editor.insertImage(welEditable, url);#}
        }
    });
}


function submit(){
      data = new FormData();
      data.append("content", editor.summernote('code'))
     data.append("title",$('#title').val())
      data.append("csrfmiddlewaretoken",'{{ csrf_token  }}');
      $.ajax({
          data: data,
          type: "POST",
          url: "/activities/activity/{{ activity_id }}/detail/edit",
          cache: false,
          contentType: false,
          processData: false,
          success: function(data) {
              $('.alert').html('Well Done, saved successfully! ').show().delay(1000).fadeOut()
        }
    });
}






</script>
{% endblock script %}

templates/activities/index.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Activities</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="/activities">Home</a></li>
                            <li class="breadcrumb-item active">Activities</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header p-2">
                                <ul class="nav nav-pills">
                                    <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Activities</a>
                                    </li>
                                </ul>
                            </div><!-- /.card-header -->
                            <div class="card-body">
                                <div class="tab-content">
                                    <div class="active tab-pane" id="timeline">
                                        <!-- The timeline -->
                                        <div class="timeline timeline-inverse">
                                            {% for activity in activities %}
                                                <div class="time-label">
                                                <span class="bg-success">
                                                  {{ activity.time }}
                                                </span>
                                                </div>
                                                <!-- timeline item -->
                                                <div>
                                                    <i class="fas fa-bookmark bg-primary"></i>

                                                    <div class="timeline-item">
                                                        <span class="time"><i class="far fa-clock"></i> {{ activity.update_time }}</span>

                                                        <h3 class="timeline-header"><a href="#">{{ activity.creator.first_name }}</a> create--
                                                            <a href="/activities/activity/{{ activity.id }}/detail"><strong>{{ activity.name }}</strong></a></h3>

                                                        <div class="timeline-body">
                                                            {{ activity.content| safe }}
                                                        </div>
                                                        <div class="timeline-footer">
                                                            <a href="/activities/activity/{{ activity.id }}/detail" class="btn btn-primary btn-sm">Detail</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            <!-- timeline time label -->
                                            <div class="time-label">
                        <span class="bg-success">
                          3 Jan. 2014
                        </span>
                                            </div>
                                            <!-- /.timeline-label -->
                                            <!-- timeline item -->
                                            <div>
                                                <i class="fas fa-camera bg-purple"></i>

                                                <div class="timeline-item">
                                                    <span class="time"><i class="far fa-clock"></i> 2 days ago</span>

                                                    <h3 class="timeline-header"><a href="#">Mina Lee</a> uploaded new
                                                        photos</h3>

                                                    <div class="timeline-body">
                                                        <img src="http://placehold.it/150x100" alt="...">
                                                        <img src="http://placehold.it/150x100" alt="...">
                                                        <img src="http://placehold.it/150x100" alt="...">
                                                        <img src="http://placehold.it/150x100" alt="...">
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- END timeline item -->
                                            <div>
                                                <i class="far fa-clock bg-gray"></i>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.tab-pane -->
                                    <!-- /.tab-pane -->
                                </div>
                                <!-- /.tab-content -->
                            </div><!-- /.card-body -->
                        </div>
                        <!-- /.nav-tabs-custom -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->


    <!-- Control Sidebar -->
    <!--
    <aside class="control-sidebar control-sidebar-dark">
    -->
    <!-- Control sidebar content goes here -->
    <!-- </aside> -->

    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.min.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "dist/js/demo.js" %}"></script>
<script>
    $("#{{ user.profile.site_id }}").attr({selected: "selected"})

    // 头像预览
    $("#id_avatar").change(function () {
        // 获取上传文件对象
        let file = $(this)[0].files[0];
        // 读取文件URL
        let reader = new FileReader();
        reader.readAsDataURL(file);
        // 阅读文件完成后触发的事件
        reader.onload = function () {
            // 读取的URL结果：this.result
            $("#avatar_img").attr("src", this.result);
        }
    });

</script>
</body>
{% endblock content %}