api/urls.py
from django.contrib import admin
from django.urls import path
from api import views




app_name = 'users'

urlpatterns = [

    # path('profile/', views.profile, name='profile'),

    path('settings/switch', views.switch, name='switch'),
    path('icons/find', views.find, name='find'),

    # path('login/', views.login, name='login',),
    # path('logout/', views.logout, name='logout'),
    # path('user/<int:user_id>/profile/', views.profile, name='profile'),
    # # path('user/<int:user_id>/profile/update/', views.profile_update, name='profile_update'),
    # path('user/<int:user_id>/pwdchange/', views.pwd_change, name='pwd_change'),

]

luckySys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('luck/', include('luck.urls')),
    path('activities/', include('activities.urls')),
    path('api/',include('api.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from users import views




app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    # path('profile/', views.profile, name='profile'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login',),
    path('logout/', views.logout, name='logout'),
    path('user/<int:user_id>/profile/', views.profile, name='profile'),
    # path('user/<int:user_id>/profile/update/', views.profile_update, name='profile_update'),
    path('user/<int:user_id>/pwdchange/', views.pwd_change, name='pwd_change'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
	# username = models.CharField(max_length=32, blank=True, null=True) // User 的first name/ last name
	# job_number = models.CharField(max_length=32, unique=True) // User 的user name
	# email = models.CharField(max_length=64, blank=True, null=True)// User email
	short_number = models.CharField(max_length=32,blank=True, null=True)
	phone_number = models.CharField(max_length=64, blank=True, null=True)
	experience = models.TextField(max_length=500, blank=True, null=True)
	skill = models.CharField(max_length=200, blank=True, null=True)
	education = models.CharField(max_length=128, blank=True, null=True)
	job = models.CharField(max_length=64, blank=True, null=True)
	avatar = models.ImageField(upload_to='avatar', default="avatar/default_qz.jpg")
	site = models.ForeignKey("Site", on_delete=models.CASCADE, blank=True, null=True)

	class Meta:
			verbose_name='User Profile'

	def __str__(self):
		return self.user.__str__()


class Site(models.Model):
	name = models.CharField(max_length=64, blank=True, null=True)

	def __str__(self):
		return self.name


class Activity(models.Model):
	name = models.CharField(max_length=200, null=False, blank=False)
	content = models.CharField(max_length=500, null=False, blank=False)
	creator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	time = models.DateField(blank=True, null=True)
	update_time = models.DateTimeField(auto_now_add=True, blank=True)
	views = models.IntegerField(default=0)

	def __str__(self):
		return self.name

users/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
import re
from users import models

NUM_LETTER = re.compile("^(?!\d+$)[\da-zA-Z_]+$")  # 数字和字母组合，不允许纯数字
FIRST_LETTER = re.compile("^[a-zA-Z\d]")  # 只能以字母开头


def account_name_fomart(Name):
	if NUM_LETTER.search(Name):
		if FIRST_LETTER.search(Name):
			return True
	return False


def email_check(email):
	pattern = re.compile(r"\"?([-_a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?")
	return re.match(pattern, email)


class RegistrationForm(forms.Form):

	# username = forms.CharField(label='Username', max_length=50)
	# email = forms.EmailField(label='Email',)
	# password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	# password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)
	username = forms.CharField(max_length=50)
	email = forms.EmailField()
	password1 = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_username(self):
		username = self.cleaned_data.get('username')
		if not account_name_fomart(username):
			raise forms.ValidationError("Your UserID must be at least 6 characters long.")
		elif len(username) < 6:
			raise forms.ValidationError("Your UserID must be at least 6 characters long.")
		elif len(username) > 50:
			raise forms.ValidationError("Your UserID is too long.")
		else:
			filter_result = User.objects.filter(username__exact=username)
			if len(filter_result) > 0:
				raise forms.ValidationError("Your UserID already exists.")

		return username

	def clean_email(self):
		email = self.cleaned_data.get('email')

		if email_check(email):
			filter_result = User.objects.filter(email__exact=email)
			if len(filter_result) > 0:
				raise forms.ValidationError("Your email already exists.")
		else:
			raise forms.ValidationError("Please enter a valid email.")

		return email

	def clean_password1(self):
		password1 = self.cleaned_data.get('password1')

		if len(password1) < 6:
			raise forms.ValidationError("Your password is too short.")
		elif len(password1) > 20:
			raise forms.ValidationError("Your password is too long.")

		return password1

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Password mismatch. Please enter again.")

		return password2


class LoginForm(forms.Form):

	username = forms.CharField(label='Username', max_length=50)
	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_username(self):
		username = self.cleaned_data.get('username')

		if email_check(username):
			filter_result = User.objects.filter(email__exact=username)
			if not filter_result:
				raise forms.ValidationError("This email does not exist.")
		else:
			filter_result = User.objects.filter(username__exact=username)
			if not filter_result:
				raise forms.ValidationError("This username does not exist. Please register first.")

		return username


class ProfileForm(forms.Form):

	first_name = forms.CharField(label='First Name', max_length=50, required=False)
	last_name = forms.CharField(label='Last Name', max_length=50, required=False)
	short_number = forms.CharField(label='Short Number', max_length=50, required=False)
	phone_number = forms.CharField(label='Phone Number', max_length=50, required=False)
	experience = forms.CharField(widget=forms.Textarea, label='Experience', max_length=500, required=False)
	skill = forms.CharField(label='Skill',max_length=200, required=False)
	education = forms.CharField(label='Education',max_length=128, required=False)
	job = forms.CharField(label="Job", max_length=64, required=False)
	site_id = forms.fields.IntegerField(widget=widgets.Select(choices=models.Site.objects.values_list('id', 'name'),))
	avatar = forms.ImageField(label='Avatar', required=False)


class PwdChangeForm(forms.Form):
	old_password = forms.CharField(label='Old password', widget=forms.PasswordInput)

	password1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

	# Use clean methods to define custom validation rules

	def clean_password1(self):
		password1 = self.cleaned_data.get('password1')

		if len(password1) < 6:
			raise forms.ValidationError("Your password is too short.")
		elif len(password1) > 20:
			raise forms.ValidationError("Your password is too long.")

		return password1

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')

		password2 = self.cleaned_data.get('password2')

		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Password mismatch. Please enter again.")

users/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.contrib.auth.models import User
from .models import UserProfile, Site
from django.contrib import auth
from .forms import RegistrationForm, LoginForm, ProfileForm, PwdChangeForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required,permission_required


# Create your views here.


def index(request):
	return HttpResponse('用戶首页')


@login_required
def logout(request):
	auth.logout(request)
	return HttpResponseRedirect("/accounts/login/")


@login_required
def pwd_change(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	user_logined = request.user
	if user != user_logined:
		return HttpResponse('You have no permission on this page')

	if request.method == "POST":
		form = PwdChangeForm(request.POST)

		if form.is_valid():

			password = form.cleaned_data['old_password']
			username = user.username

			user = auth.authenticate(username=username, password=password)

			if user is not None and user.is_active:
				new_password = form.cleaned_data['password2']
				user.set_password(new_password)
				user.save()
				return HttpResponseRedirect("/accounts/login/")

			else:
				return render(request, 'users/pwd_change.html', {'form': form, 'user': user, 'message': 'Old password is wrong. Try again'})
	else:
		form = PwdChangeForm()

	return render(request, 'users/pwd_change.html', {'form': form, 'user': user})



# @login_required
# def profile_update(request, user_id):
# 	user = get_object_or_404(User, pk=user_id)
# 	user_profile = get_object_or_404(UserProfile, user=user)
# 	user_logined = request.user
# 	if user != user_logined:
# 		return HttpResponse('You have no permission on this page')
# 	if request.method == "POST":
# 		form = ProfileForm(request.POST, request.FILES)
# 		print("post is on")
#
# 		if form.is_valid():
# 			user.first_name = form.cleaned_data['first_name']
# 			# user.last_name = form.cleaned_data['last_name']
# 			user.save()
#
# 			user_profile.short_number = form.cleaned_data['short_number']
# 			user_profile.phone_number = form.cleaned_data['phone_number']
# 			user_profile.avatar = form.cleaned_data['avatar']
# 			user_profile.site = Site.objects.get(id=form.cleaned_data['site_id'])
# 			user_profile.save()
#
# 			return HttpResponseRedirect(reverse('users:profile', kwargs={'user_id': user.id}))
# 	else:
# 		default_data = {'first_name': user.first_name, 'last_name': user.last_name,'short_number': user_profile.short_number, 'phone_number': user_profile.phone_number, }
# 		form = ProfileForm(default_data)
#
# 	return render(request, 'users/profile_update.html', {'form': form, 'user': user})


@login_required
def profile(request, user_id):
	user = get_object_or_404(User, pk=user_id)
	user_profile = get_object_or_404(UserProfile, user=user)
	user_logined = request.user
	if user != user_logined:
		return HttpResponse('You have no permission on this page')
	if request.method == "POST":
		form = ProfileForm(request.POST, request.FILES)
		if form.is_valid():
			user.first_name = form.cleaned_data['first_name']
			# user.last_name = form.cleaned_data['last_name']
			user.save()

			user_profile.short_number = form.cleaned_data['short_number']
			user_profile.phone_number = form.cleaned_data['phone_number']
			user_profile.experience = form.cleaned_data['experience']
			user_profile.job = form.cleaned_data['job']
			user_profile.skill = form.cleaned_data['skill']
			user_profile.education = form.cleaned_data['education']
			if form.cleaned_data['avatar'] is not None:
				user_profile.avatar = form.cleaned_data['avatar']
			else:
				print("User dose not upload avatar")
			user_profile.site = Site.objects.get(id=form.cleaned_data['site_id'])
			user_profile.save()

			return HttpResponseRedirect(reverse('users:profile', kwargs={'user_id': user.id}))
	else:
		default_data = {'first_name': user.first_name, 'last_name': user.last_name,'short_number': user_profile.short_number, 'phone_number': user_profile.phone_number,'experience':user_profile.experience, 'education':user_profile.education,'skill':user_profile.skill,'job':user_profile.job }
		form = ProfileForm(default_data)
	return render(request, 'users/profile.html', {'form': form, 'user': user})


def register(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			email = form.cleaned_data['email'].lower()
			password = form.cleaned_data['password2']

			# 使用内置User自带create_user方法创建用户，不需要使用save()
			user = User.objects.create_user(username=username, password=password, email=email)

			# 如果直接使用objects.create()方法后不需要使用save()
			user_profile = UserProfile(user=user)
			user_profile.save()

			return HttpResponseRedirect("/accounts/login/")

	else:
		form = RegistrationForm()
	print('aaa')

	return render(request, 'users/registration.html', {'form': form})


def login(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = auth.authenticate(username=username, password=password)
			if user is not None and user.is_active:
				auth.login(request, user)
				return HttpResponseRedirect(reverse('users:profile', kwargs={'user_id': user.id}))

			else:
				# 登陆失败
				return render(request, 'users/login.html', {'form': form, 'message': 'Your account is not active, please contact with tim zhong.'})
		else:
			return render(request, 'users/login.html', {'form': form, 'message': 'Wrong userID or password. Please try again.'})
	else:
		form = LoginForm()
	return render(request, 'users/login.html', {'form': form})

templates/users/login.bak.html
{% extends 'index.html' %}
{% block content %}
{% if message %}
 {{ message }}
{% endif %}
<div class="form-wrapper container col-md-4 col-md-offset-4" style="margin-top: 10%; background-color: #ffffff;border-radius:5px;">
   <form method="post" action="" enctype="multipart/form-data" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
           <div class="fieldWrapper form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        <div class="col-sm-5">

        {{ field }}
        </div>
        {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
           </div>
        {% endfor %}
      <div class="button-wrapper submit col-md-offset-5">
            <button type="submit" class="btn btn-success">Login</button>
            <button type="button" class="btn btn-link"><a href="/accounts/register">Register</a></button>
      </div>
   </form>
</div>
    <script>
        $('#id_username').addClass('form-control')
        $('#id_password').addClass('form-control')
        $('label').addClass('col-sm-4 control-label')
    </script>
{% endblock %}

templates/users/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>QT Annual Activities | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>QT </b> Activities</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Sign in to start</p>

      <form action="" method="post">
          {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="username" placeholder="UserID">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="password" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
          <div class="row">
                  <p style="color: red;">{{ message }}</p>
          </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
<!--
      <p class="mb-1">
        <a href="#">I forgot my password</a>
      </p>
      -->
      <p class="mb-0">
        <a href="/accounts/register" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

</body>
</html>

templates/users/profile.bak.html
{% extends 'index.html' %}
{% block content %}
    <div class="form-wrapper container col-md-6 col-md-offset-3" style="margin-top: 1%; background-color: #ffffff;border-radius:5px;min-height:700px; min-width: 900px">
    <div class="form-wrapper container col-md-8  " style="margin-top: 1%; background-color: #ffffff;border-radius:5px;">
<h3>Account Info</h3>
<ul>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Username:</strong></div> <div class="col-md-offset-1"> {{ user.username }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Email:</strong></div> <div class="col-md-offset-1"> {{ user.email }}</div> </div></li>
</ul>
<h3>My Profile</h3>
<ul>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>FirstName:</strong></div> <div class="col-md-offset-1"> {{ user.first_name }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>LastName:</strong></div> <div class="col-md-offset-1"> {{ user.last_name }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>ShortNumber:</strong></div> <div class="col-md-offset-1"> {{ user.profile.short_number }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Telephone:</strong></div> <div class="col-md-offset-1"> {{ user.profile.phone_number }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Site:</strong></div> <div class="col-md-offset-1"> {{ user.profile.site }}</div> </div></li>


</ul>


    </div>
{#        <div class="col-md-offset-10 clearfix" style="margin-top: 2%">  <img src="/media/{{ user.profile.avatar }}" class="img-thumbnail" style="width: 140px; height: 140px;" alt="Avatar"><strong>Avatar</strong></div>#}
{#    <div class="col-md-offset-8 clearfix" style="margin-bottom: 2%">#}
{#    {% if user.is_authenticated %}#}
{#    <a href="{% url 'users:profile_update' user.id %}">Edit Profile</a>#}
{#| <a href="{% url 'users:pwd_change' user.id %}">Change Password </a>#}
{#| <a href="{% url 'users:logout' %}">Logout</a>#}
{#{% endif %}#}
{#</div>#}
    </div>
    <script>
    $('.col-md-3').addClass('text-right')
    $('.row').css('min-width','540px')
    </script>
{% endblock %}

templates/users/profile_update.html
{% extends 'index.html' %}
{% block content %}
    <div class="form-wrapper container col-md-6 col-md-offset-3" style="margin-top: 1%; background-color: #ffffff;border-radius:5px;min-height:700px">
    <div class="form-wrapper container col-md-8  " style="margin-top: 1%; background-color: #ffffff;border-radius:5px;">
<h2>Account Info</h2>
<ul>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Username:</strong></div> <div class="col-md-offset-1"> {{ user.username }}</div> </div></li>
    <li> <div class="row">  <div class="col-md-3 col-md-offset-1"><strong>Email:</strong></div> <div class="col-md-offset-1"> {{ user.email }}</div> </div></li>

</ul>
<h2>Update My Profile</h2>

<div class="form-wrapper">
   <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
           <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
           </div>
        {% endfor %}
      <div class="button-wrapper submit">
         <input type="submit" value="Update" />
      </div>
   </form>
</div>

<a href="{% url 'users:logout' %}">Logout</a> |
<a href="{% url 'users:pwd_change' user.id %}">Password change</a>
    </div>
    </div>
    <script>
    $('.col-md-3').addClass('text-right')
    </script>
{% endblock %}

templates/users/pwd_change.html
{% block content %}
<h2>Change Password</h2>
{% if message %}
 {{ message }}
{% endif %}
<div class="form-wrapper">
   <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
           <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
           </div>
        {% endfor %}
      <div class="button-wrapper submit">
         <input type="submit" value="Submit" />
      </div>
   </form>
    <a href="/accounts/logout/">Logout</a>
</div>
{% endblock %}

templates/users/registration.bak.html
{% block content %}
<div class="form-wrapper">
   <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
           <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
             <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
           </div>
        {% endfor %}
      <div class="button-wrapper submit">
         <input type="submit" value="Submit" />
      </div>
   </form>
</div>
{% endblock %}

templates/users/registration.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>QT Annual Activities | Registration</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "plugins/fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static "dist/css/adminlte.min.css" %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="register-logo">
        <a href="#"><b>QT</b> Activities</a>
    </div>

    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">Register a new membership</p>
       

            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="username" placeholder="User ID">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="email" class="form-control" name="email" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" name="password1" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" name="password2" placeholder="Retype password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
            <div  >
                {% for field in form %}
                                {{ field.errors }}
                {% endfor %}
            </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree">
                            <label for="agreeTerms">
                                I agree to the <a href="#">terms</a>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <a href="../login" class="text-center">I already have a membership</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
<!-- /.register-box -->


<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

<script>
    $('.formd input').addClass('form-control')
    $('.errorlist li').css({"color":"red"})

</script>
</body>
</html>